version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: nike-workshop-backend-base
    IMAGE_TAG: release

phases:
  pre_build:
    commands:
      # Set up environment variables
      - cd $CODEBUILD_SRC_DIR/trivia-backend/base
      - AWS_ACCOUNT_ID=`echo $CODEBUILD_BUILD_ARN | awk -F":" '{print $5}'`
      - ECR_REPO=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - docker login -u AWS -p $(aws ecr get-login-password --region us-east-1) 339263341917.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      # Build Docker image
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG
      - docker push $ECR_REPO:$IMAGE_TAG
