version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - cd chat-bot/bot
      - npm install -g npm@latest
      - npm ci
      - cd ..
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket $ARTIFACTS_BUCKET --output-template-file TriviaGameChatBotProd.template.yaml
      - sed 's/api.nike-workshop.com/api-test.nike-workshop.com/g' TriviaGameChatBotProd.template.yaml > TriviaGameChatBotTest.template.yaml
      - cp StackConfig.json StackConfigTest.json
      - cp StackConfig.json StackConfigProd.json

artifacts:
  files:
    - chat-bot/TriviaGameChatBotTest.template.yaml
    - chat-bot/TriviaGameChatBotProd.template.yaml
    - chat-bot/StackConfigTest.json
    - chat-bot/StackConfigProd.json
  discard-paths: yes
